### ISSUE TITLE
Error undefined is not an object (evaluating 'require(_dependencyMap

### ISSUE THREAD

**Issue by impactcolor** [skantus/react-native-firebase-redux-authentication#1]
Hi I'm getting this error running Node v8.11.3
22:53:36: TypeError: undefined is not an object (evaluating 'require(_dependencyMap[0], './navigators/createContainedStackNavigator').default')

This error is located at:
    in Router (created by Connect(Router))
    in Connect(Router) (at routes.js:22)
    in Provider (at routes.js:21)
    in Routes (at App.js:6)

**Comment by skantus** [comment]
Hi @impactcolor thank you for reporting the issue, let me check it and soon I'll let you know.

**Comment by skantus** [comment]
@impactcolor the project has been updated, now is _working_ with the last versions of react. ✅ 

⚫️ "react": "16.4.1"
⚫️ "react-native": "0.56.1"
⚫️ "redux": "^4.0.0"
⚫️ "react-redux": "^5.0.7"

Happy coding 💯
