### ISSUE TITLE
Can't changes anything

### ISSUE THREAD

**Issue by ahmadmnaa** [skantus/react-native-firebase-redux-authentication#2]
When I'm trying to change the color or anything for the design I am getting the below issue -->
.overrid is not allowed in preset options (null)

**Comment by skantus** [comment]
Hi @ahmadmnaa thank you for reporting this issue, do you have more information about it, screenshots?

Let me see what happened.

**Comment by ahmadmnaa** [comment]
for example when I change the below code

`render() {
    const { login, loading } = this.props;
    const { scrollView, imageBox, image, loginBox } = styles;
    return (
      <KeyboardAwareScrollView style={scrollView}>
        <View style={imageBox}>
          <Image style={image} source={FIREBASE_LOGO} />
        </View>
        <View style={loginBox}>
          {loading ? (
            <LoadingIndicator color="#ffffff" size="large" />
          ) : (
            <BasicFormComponent buttonTitle={'login'} onButtonPress={login} />
          )}
        </View>
        <View>{loading ? null : <Button onPress={Actions.signup} title="Signup" color="white" />}</View>
      </KeyboardAwareScrollView>
    );
  }
}`

to -->
`render() {
    const { login, loading } = this.props;
    const { scrollView, imageBox, image, loginBox } = styles;
    return (
      <KeyboardAwareScrollView style={scrollView}>
        <View style={imageBox}>
          <Image style={image} source={FIREBASE_LOGO} />
        </View>
        <View style={loginBox}>
          {loading ? (
            <LoadingIndicator color="#ffff0f" size="large" />
          ) : (
            <BasicFormComponent buttonTitle={'login'} onButtonPress={login} />
          )}
        </View>
        <View>{loading ? null : <Button onPress={Actions.signup} title="Signup" color="white" />}</View>
      </KeyboardAwareScrollView>
    );
  }
}`

i'm getting the below Exception-->

![simulator screen shot - iphone 8 plus - 2018-10-15 at 17 49 15](https://user-images.githubusercontent.com/15180612/47005366-458e5980-d13c-11e8-8cee-88830d13e92b.png)

And this happened when i'm trying to change anything

**Comment by ahmadmnaa** [comment]
Hi @skantus  any updates?

**Comment by skantus** [comment]
Hi @ahmadmnaa I'm working on it, I hope to have updates today.

**Comment by skantus** [comment]
Hi @ahmadmnaa I was trying to run your code: _I changed the color 'ffffff' by 'ffff0f'_ and I haven't go any problems but can be a ***cache*** error.

Try this:

Run in your terminal:

1. `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/haste-map-react-native-packager-* && rm -rf node_modules/ && npm install`

2. `npm start -- --reset-cache`

3. `react-native run-ios`

***Results:***

<img width="421" alt="captura de pantalla 2018-10-17 a las 18 43 58" src="https://user-images.githubusercontent.com/4986411/47102455-1ca1bd80-d23d-11e8-987e-8ee8559e497c.png">
