### ISSUE TITLE
error: bundling failed: Error

### ISSUE THREAD

**Issue by ilyasisik** [skantus/react-native-firebase-redux-authentication#3]
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `components/routes` from `/WebstormProjects/react-native-firebase-redux-authentication/App.js`: Module `components/routes` does not exist in the Haste module map

**Comment by skantus** [comment]
Hi @iztimbilisim thanks for report this `issue`, we will to review the problem and soon we let you know about it.

**Comment by skantus** [comment]
Hi @iztimbilisim sorry for late, you can try now to run the project, I've updated `react-native`, `react` and other dependencies to ***latest*** versiones and are working perfectly.

`iOS 12` Supported! 🎉 

<img width="430" alt="captura de pantalla 2018-10-27 a las 20 22 41" src="https://user-images.githubusercontent.com/4986411/47607946-0ce95c80-da27-11e8-9cd4-27b7205b1b3f.png">

To ensure the correct installation I recommended use the next commands:

```
1. cd && rm -rf .rncache
2. watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/haste-map-react-native-packager-* && rm -rf node_modules/ && npminstall
3. npm start -- --reset-cache
4. react-native run-ios
```

Thanks for reporting and ***_Happy coding_*** 😆

**Comment by gloomcheng** [comment]
I faced same issue, does this issue could be related about https://stackoverflow.com/a/44410874 ?

**Comment by skantus** [comment]
Candidate Name: **_Alejo Castaño._**

Tasks: **_task 1 and 3._**

Time:

- task 1: 2h.
- task 3: 2h.

Notes:

- Used patterns:

```
Atomic Design
Function component
Destructuring props
Children types
Array as children
Render prop
Style component
Layout component
Functional programming
Single principle responsibility
...
```

- Utils:

```
Small Components
Unit test
Restful
Utils / moment
```
